[2025-04-26 14:24:14,252 INFO] [run_gptuner.py:<module>:107] Input arguments: Namespace(config='src/exp_configs/tpch/gpt-3.5-turbo-overall.yml', folder='default', process='whole', db='postgres', database='tpch_workload', test='tpch', timeout=180, seed=100, result_path='./experiments_results/tpch/gpt-3.5-turbo-overall_202504261424', model='gpt-3.5-turbo-0125', restart_cmd='echo 251314 | sudo -S docker restart benchbase', recover_script='./scripts/recover_docker_postgres.sh', user='postgres', password='postgres')
[2025-04-26 14:27:57,461 WARNING] [run_gptuner.py:<module>:156] 'checkpoint_segments' is not in postgres
