[2025-04-10 19:33:47,456 INFO] [run_gptuner.py:<module>:99] Input arguments: Namespace(config='src/exp_configs/gpt4-4o-mini-overall.yml', db='postgres', database='tpcc_workload', test='tpcc', timeout=180, seed=100, result_path='./experiments_results/gpt4-4o-mini-overall_202504101933', model='gpt-4o-mini', restart_cmd='sudo restart tpcc_workload', recover_script='./scripts/recover_docker_postgres.sh', user='postgres', password='postgres')
[2025-04-10 19:36:14,198 WARNING] [run_gptuner.py:<module>:146] 'checkpoint_segments' is not in postgres
