[2025-04-10 21:22:22,963 INFO] [run_gptuner.py:<module>:99] Input arguments: Namespace(config='src/exp_configs/gpt-4o-overall.yml', db='postgres', database='tpcc_workload', test='tpcc', timeout=180, seed=100, result_path='./experiments_results/gpt-4o-overall_202504102122', model='gpt-4o', restart_cmd='sudo docker restart tpcc_workload', recover_script='./scripts/recover_docker_postgres.sh', user='postgres', password='postgres')
[2025-04-10 21:23:43,009 WARNING] [run_gptuner.py:<module>:146] 'checkpoint_segments' is not in postgres
