[2025-04-13 15:36:29,813 INFO] [run_gptuner.py:<module>:107] Input arguments: Namespace(config='src/exp_configs/gpt-4o-overall.yml', folder='default', process='whole', db='postgres', database='postgres', test='tpcc', timeout=180, seed=100, result_path='./experiments_results/gpt-4o-overall_202504131536', model='gpt-4o', restart_cmd='echo 251314 | sudo -S docker restart tpcc_workload', recover_script='./scripts/recover_docker_postgres.sh', user='postgres', password='postgres')
[2025-04-13 15:38:06,470 WARNING] [run_gptuner.py:<module>:156] 'checkpoint_segments' is not in postgres
[2025-04-13 15:38:06,470 WARNING] [run_gptuner.py:<module>:156] 'wal_keep_segments' is not in postgres
[2025-04-13 16:05:09,931 INFO] [coarse_space.py:__init__:21] Coarse Configuration Space:
[2025-04-13 16:43:18,876 INFO] [fine_space.py:__init__:26] Fine Configuration Space:
