[2025-04-11 14:16:17,460 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 14:16:17,469 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'on';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 14:16:17,547 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-11 14:16:17,568 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 14:16:17,588 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'all';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 14:16:17,588 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 14:16:37,718 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 14:17:01,329 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 14:17:01,337 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 14:17:01,350 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set deadlock_timeout to '0';" to update dbms for error: 0 ms is outside the valid range for parameter "deadlock_timeout" (1 .. 2147483647)

[2025-04-11 14:17:01,420 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-11 14:17:01,427 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 14:17:01,436 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 14:17:01,454 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'all';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 14:17:01,455 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 14:17:21,614 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 14:17:45,245 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 14:17:45,253 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 14:17:45,266 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set deadlock_timeout to '0';" to update dbms for error: 0 ms is outside the valid range for parameter "deadlock_timeout" (1 .. 2147483647)

[2025-04-11 14:17:45,329 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-11 14:17:45,348 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '10000';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 14:17:45,367 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'top';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 14:17:45,367 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 14:18:05,521 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 14:18:29,297 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 14:18:29,310 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 14:18:29,323 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set deadlock_timeout to '0';" to update dbms for error: 0 ms is outside the valid range for parameter "deadlock_timeout" (1 .. 2147483647)

[2025-04-11 14:18:29,399 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 14:18:29,409 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '2550';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 14:18:29,427 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'all';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 14:18:29,427 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 14:18:49,543 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 14:19:13,253 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 14:19:13,262 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'on';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 14:19:13,276 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set deadlock_timeout to '0';" to update dbms for error: 0 ms is outside the valid range for parameter "deadlock_timeout" (1 .. 2147483647)

[2025-04-11 14:19:13,358 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 14:19:13,369 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '536873411';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 14:19:13,388 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'none';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 14:19:13,388 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 14:19:33,584 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 14:19:57,140 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 14:19:57,148 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 14:19:57,245 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 14:19:57,264 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'top';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 14:19:57,265 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 14:19:57,265 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-11 14:20:17,442 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 14:20:41,221 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 14:20:41,229 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'on';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 14:20:41,244 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set deadlock_timeout to '0';" to update dbms for error: 0 ms is outside the valid range for parameter "deadlock_timeout" (1 .. 2147483647)

[2025-04-11 14:20:41,323 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 14:20:41,333 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '10000';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 14:20:41,351 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'none';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 14:20:41,352 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 14:21:01,519 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 14:21:25,366 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 14:21:25,375 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'on';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 14:21:25,454 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-11 14:21:25,473 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 14:21:25,492 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'top';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 14:21:25,493 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 14:21:25,493 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-11 14:21:45,592 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 14:22:09,200 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 14:22:09,209 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'on';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 14:22:09,302 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 14:22:09,313 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '268439205';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 14:22:09,331 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'all';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 14:22:09,331 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 14:22:29,506 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 14:22:53,221 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 14:22:53,229 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 14:22:53,310 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-11 14:22:53,328 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 14:22:53,346 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'none';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 14:22:53,346 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 14:23:13,462 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 14:23:37,125 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 14:23:37,134 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 14:23:37,248 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '10000';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 14:23:37,269 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'all';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 14:23:37,270 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 14:25:09,143 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 14:25:09,152 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'on';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 14:25:09,164 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set deadlock_timeout to '0';" to update dbms for error: 0 ms is outside the valid range for parameter "deadlock_timeout" (1 .. 2147483647)

[2025-04-11 14:25:09,248 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '10000';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 14:25:09,268 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'none';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 14:25:09,268 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 14:26:39,853 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 14:26:39,861 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'on';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 14:26:39,875 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set deadlock_timeout to '0';" to update dbms for error: 0 ms is outside the valid range for parameter "deadlock_timeout" (1 .. 2147483647)

[2025-04-11 14:26:39,960 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '10000';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 14:26:39,979 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'top';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 14:26:39,979 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 14:27:00,097 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 14:27:23,803 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 14:27:23,811 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 14:27:23,922 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '10000';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 14:27:23,940 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'top';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 14:27:23,941 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 14:27:23,941 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-11 14:27:44,112 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 14:28:07,682 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 14:28:07,690 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 14:28:07,704 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set deadlock_timeout to '0';" to update dbms for error: 0 ms is outside the valid range for parameter "deadlock_timeout" (1 .. 2147483647)

[2025-04-11 14:28:07,797 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '10000';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 14:28:07,817 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'top';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 14:28:07,818 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 14:28:07,819 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-11 14:28:27,960 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 14:28:51,558 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 14:28:51,566 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 14:28:51,662 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '10000';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 14:28:51,680 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'none';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 14:28:51,681 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 14:29:11,827 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 14:29:35,413 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 14:29:35,420 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 14:29:35,436 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set deadlock_timeout to '0';" to update dbms for error: 0 ms is outside the valid range for parameter "deadlock_timeout" (1 .. 2147483647)

[2025-04-11 14:29:35,524 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '3775';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 14:29:35,542 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'all';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 14:29:35,543 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 14:29:55,755 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 14:30:19,537 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 14:30:19,546 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 14:30:19,648 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '10000';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 14:30:19,668 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'all';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 14:30:19,668 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 14:30:19,669 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-11 14:30:39,805 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 14:31:03,382 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 14:31:03,393 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'on';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 14:31:03,405 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set deadlock_timeout to '0';" to update dbms for error: 0 ms is outside the valid range for parameter "deadlock_timeout" (1 .. 2147483647)

[2025-04-11 14:31:03,497 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '10000';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 14:31:03,518 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'none';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 14:31:03,519 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 14:31:24,981 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 14:31:48,529 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 14:31:48,537 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'on';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 14:31:48,619 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-11 14:31:48,636 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 14:31:48,657 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'top';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 14:31:48,657 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 14:32:08,844 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 14:32:32,597 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 14:32:32,604 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 14:32:32,617 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set deadlock_timeout to '0';" to update dbms for error: 0 ms is outside the valid range for parameter "deadlock_timeout" (1 .. 2147483647)

[2025-04-11 14:32:32,686 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-11 14:32:32,704 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 14:32:32,722 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'top';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 14:32:32,723 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 14:32:52,927 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 14:33:16,534 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 14:33:16,542 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 14:33:16,627 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-11 14:33:16,647 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '268439205';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 14:33:16,665 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'all';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 14:33:16,666 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 14:33:36,766 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 14:34:00,364 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 14:34:00,372 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 14:34:00,384 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set deadlock_timeout to '0';" to update dbms for error: 0 ms is outside the valid range for parameter "deadlock_timeout" (1 .. 2147483647)

[2025-04-11 14:34:00,474 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '10000';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 14:34:00,494 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'top';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 14:34:00,494 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 14:34:20,649 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 14:34:44,232 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 14:34:44,240 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 14:34:44,344 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 14:34:44,362 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'top';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 14:34:44,362 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 14:35:04,530 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 14:35:28,323 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 14:35:28,331 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 14:35:28,431 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '10000';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 14:35:28,452 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'all';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 14:35:28,453 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 14:36:59,127 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 14:36:59,148 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'on';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 14:36:59,187 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set deadlock_timeout to '0';" to update dbms for error: 0 ms is outside the valid range for parameter "deadlock_timeout" (1 .. 2147483647)

[2025-04-11 14:36:59,385 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-11 14:36:59,405 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 14:36:59,435 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '10000';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 14:36:59,492 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'all';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 14:36:59,493 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 14:37:19,738 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 14:37:43,442 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 14:37:43,450 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'on';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 14:37:43,463 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set deadlock_timeout to '0';" to update dbms for error: 0 ms is outside the valid range for parameter "deadlock_timeout" (1 .. 2147483647)

[2025-04-11 14:37:43,550 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '536873411';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 14:37:43,568 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'none';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 14:37:43,569 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 14:38:03,784 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 14:38:27,383 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 14:38:27,391 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 14:38:27,404 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set deadlock_timeout to '0';" to update dbms for error: 0 ms is outside the valid range for parameter "deadlock_timeout" (1 .. 2147483647)

[2025-04-11 14:38:27,470 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-11 14:38:27,476 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 14:38:27,486 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 14:38:27,504 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'top';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 14:38:27,505 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 14:38:49,028 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 14:39:12,653 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 14:39:12,661 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 14:39:12,744 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-11 14:39:12,763 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 14:39:12,782 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'top';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 14:39:12,782 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 14:39:12,783 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-11 14:40:50,186 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 14:40:50,194 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'on';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 14:40:50,275 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-11 14:40:50,282 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 14:40:50,291 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 14:40:50,310 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'top';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 14:40:50,310 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 14:40:50,311 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-11 14:41:12,483 ERROR] [postgres.py:update_dbms:117] Failed to execute "drop database if exists tpcc_template" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 14:41:12,483 ERROR] [postgres.py:update_dbms:117] Failed to execute "create database tpcc_template with template benchbase" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 14:41:12,483 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 16:15:27,363 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 16:15:27,371 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 16:15:27,479 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 16:15:27,490 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 16:15:27,513 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'top';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 16:15:27,514 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 16:15:27,514 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-11 16:17:05,165 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 16:17:05,175 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'on';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 16:17:05,188 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set deadlock_timeout to '0';" to update dbms for error: 0 ms is outside the valid range for parameter "deadlock_timeout" (1 .. 2147483647)

[2025-04-11 16:17:05,260 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 16:17:05,271 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 16:17:05,292 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'top';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 16:17:05,292 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 16:17:05,293 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-11 16:17:25,447 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 16:17:49,318 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 16:17:49,327 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 16:17:49,422 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 16:17:49,431 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 16:17:49,450 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'all';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 16:17:49,451 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 16:19:20,813 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 16:19:20,823 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 16:19:20,916 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 16:19:20,926 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '10000';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 16:19:20,944 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'all';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 16:19:20,945 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 16:20:51,952 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 16:20:51,961 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'on';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 16:20:52,060 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 16:20:52,070 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '10000';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 16:20:52,089 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'none';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 16:20:52,090 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 16:22:23,361 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 16:22:23,370 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'on';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 16:22:23,470 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '229412394';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 16:22:23,491 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'all';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 16:22:23,491 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 16:22:43,662 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 16:23:07,668 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 16:23:07,675 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 16:23:07,691 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set deadlock_timeout to '0';" to update dbms for error: 0 ms is outside the valid range for parameter "deadlock_timeout" (1 .. 2147483647)

[2025-04-11 16:23:07,770 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 16:23:07,781 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '700719893';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 16:23:07,803 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'top';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 16:23:07,804 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 16:23:28,014 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 16:23:51,921 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 16:23:51,929 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'on';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 16:23:52,011 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-11 16:23:52,018 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 16:23:52,028 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 16:23:52,050 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'top';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 16:23:52,051 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 16:24:13,918 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 16:24:37,547 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 16:24:37,555 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 16:24:37,655 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 16:24:37,666 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 16:24:37,686 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'top';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 16:24:37,687 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 16:24:37,688 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-11 16:26:15,664 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 16:26:15,676 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 16:26:15,759 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-11 16:26:15,766 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 16:26:15,775 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 16:26:15,792 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'top';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 16:26:15,793 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 16:26:15,793 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-11 16:27:53,316 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 16:27:53,325 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 16:27:53,414 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-11 16:27:53,421 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 16:27:53,431 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '10000';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 16:27:53,449 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'none';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 16:27:53,449 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 16:27:53,450 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-11 16:29:32,149 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 16:29:32,158 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'on';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 16:29:32,243 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 16:29:32,253 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '10000';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 16:29:32,271 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'none';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 16:29:32,272 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 16:29:32,272 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-11 16:31:15,537 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 16:31:15,545 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'on';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 16:31:15,557 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set deadlock_timeout to '0';" to update dbms for error: 0 ms is outside the valid range for parameter "deadlock_timeout" (1 .. 2147483647)

[2025-04-11 16:31:15,621 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-11 16:31:15,628 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 16:31:15,638 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 16:31:15,657 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'top';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 16:31:15,657 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 16:31:15,657 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-11 16:32:55,508 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 16:32:55,516 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 16:32:55,612 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 16:32:55,623 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '10000';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 16:32:55,642 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'none';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 16:32:55,643 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 16:32:55,643 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-11 16:33:15,890 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 16:33:39,715 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 16:33:39,722 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'on';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 16:33:39,802 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-11 16:33:39,808 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 16:33:39,818 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '860606422';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 16:33:39,837 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'all';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 16:33:39,838 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 16:33:39,838 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-11 16:34:00,017 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 16:34:23,644 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 16:34:23,652 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'on';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 16:34:23,666 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set deadlock_timeout to '0';" to update dbms for error: 0 ms is outside the valid range for parameter "deadlock_timeout" (1 .. 2147483647)

[2025-04-11 16:34:23,751 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 16:34:23,769 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'none';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 16:34:23,770 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 16:34:44,093 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 16:35:07,963 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 16:35:07,972 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 16:35:07,988 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set deadlock_timeout to '0';" to update dbms for error: 0 ms is outside the valid range for parameter "deadlock_timeout" (1 .. 2147483647)

[2025-04-11 16:35:08,075 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '1068621175';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 16:35:08,096 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'all';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 16:35:08,097 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 16:35:08,098 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-11 16:35:30,410 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 16:35:53,969 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 16:35:53,976 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 16:35:54,056 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-11 16:35:54,062 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 16:35:54,074 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 16:35:54,093 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'top';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 16:35:54,093 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 16:35:54,094 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-11 16:37:36,099 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 16:37:36,107 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 16:37:36,200 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 16:37:36,210 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 16:37:36,229 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'none';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 16:37:36,229 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 16:37:36,230 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-11 16:39:13,724 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 16:39:13,732 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 16:39:13,824 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 16:39:13,834 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 16:39:13,853 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'top';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 16:39:13,854 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 16:40:44,771 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 16:40:44,779 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 16:40:44,872 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 16:40:44,883 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 16:40:44,903 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'top';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 16:40:44,903 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 16:40:44,904 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-11 16:42:16,738 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 16:42:16,748 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 16:42:16,825 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-11 16:42:16,832 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 16:42:16,842 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 16:42:16,861 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'top';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 16:42:16,861 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 16:43:47,881 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 16:43:47,889 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'on';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 16:43:47,966 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-11 16:43:47,973 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 16:43:47,983 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '251167439';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 16:43:48,001 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'none';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 16:43:48,001 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 16:43:48,002 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-11 16:45:28,162 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 16:45:28,170 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'on';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 16:45:28,253 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-11 16:45:28,260 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 16:45:28,270 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '10000';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 16:45:28,288 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'none';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 16:45:28,289 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 16:45:48,619 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 16:46:13,136 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 16:46:13,146 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 16:46:13,160 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set deadlock_timeout to '0';" to update dbms for error: 0 ms is outside the valid range for parameter "deadlock_timeout" (1 .. 2147483647)

[2025-04-11 16:46:13,223 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-11 16:46:13,241 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 16:46:13,260 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'none';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 16:46:13,261 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 16:46:35,352 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 16:46:58,958 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 16:46:58,967 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 16:46:59,047 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-11 16:46:59,054 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 16:46:59,063 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '34032686';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 16:46:59,086 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'none';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 16:46:59,086 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 16:46:59,087 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-11 16:48:32,754 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 16:48:32,764 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'on';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 16:48:32,889 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 16:48:32,910 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'none';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 16:48:32,910 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 16:48:53,054 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 16:49:16,885 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 16:49:16,893 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'on';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 16:49:17,002 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 16:49:17,023 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'top';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 16:49:17,024 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 16:49:37,236 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 16:50:00,993 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 16:50:01,002 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 16:50:01,106 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 16:50:01,125 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'top';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 16:50:01,126 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 16:51:32,062 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 16:51:32,069 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 16:51:32,156 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 16:51:32,165 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 16:51:32,183 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'none';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 16:51:32,183 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 16:53:10,100 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 16:53:10,109 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 16:53:10,192 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-11 16:53:10,214 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 16:53:10,233 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'top';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 16:53:10,234 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 16:55:04,868 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 16:55:04,876 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 16:55:04,960 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-11 16:55:04,979 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 16:55:04,999 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'all';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 16:55:05,000 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 16:56:44,368 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 16:56:44,377 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 16:56:44,391 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set deadlock_timeout to '0';" to update dbms for error: 0 ms is outside the valid range for parameter "deadlock_timeout" (1 .. 2147483647)

[2025-04-11 16:56:44,476 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 16:56:44,487 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '10000';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 16:56:44,509 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'all';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 16:56:44,509 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 16:56:44,510 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-11 16:58:27,360 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 16:58:27,369 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 16:58:27,481 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 16:58:27,502 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'all';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 16:58:27,503 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 16:58:27,503 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-11 17:00:10,381 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 17:00:10,389 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'on';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 17:00:10,485 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '775136';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 17:00:10,502 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'none';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 17:00:10,503 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 17:00:10,503 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-11 17:00:30,701 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 17:00:54,345 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 17:00:54,354 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 17:00:54,451 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 17:00:54,462 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 17:00:54,481 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'all';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 17:00:54,482 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 17:00:54,483 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-11 17:02:32,920 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 17:02:32,927 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 17:02:33,016 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 17:02:33,026 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 17:02:33,044 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'all';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 17:02:33,044 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 17:04:10,885 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 17:04:10,895 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 17:04:10,909 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set deadlock_timeout to '0';" to update dbms for error: 0 ms is outside the valid range for parameter "deadlock_timeout" (1 .. 2147483647)

[2025-04-11 17:04:10,988 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 17:04:11,007 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'all';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 17:04:11,007 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 17:04:11,008 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-11 17:05:54,049 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 17:05:54,058 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 17:05:54,071 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set deadlock_timeout to '0';" to update dbms for error: 0 ms is outside the valid range for parameter "deadlock_timeout" (1 .. 2147483647)

[2025-04-11 17:05:54,153 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '10000';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 17:05:54,171 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'all';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 17:05:54,172 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 17:07:33,349 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 17:07:33,359 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 17:07:33,444 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-11 17:07:33,451 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 17:07:33,462 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 17:07:33,483 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'all';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 17:07:33,483 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 17:07:33,484 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-11 17:07:55,367 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 17:08:19,011 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 17:08:19,020 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 17:08:19,101 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-11 17:08:19,107 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 17:08:19,117 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 17:08:19,136 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'top';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 17:08:19,137 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 17:09:50,153 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 17:09:50,162 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 17:09:50,251 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-11 17:09:50,258 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 17:09:50,268 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 17:09:50,287 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'top';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 17:09:50,288 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 17:10:10,511 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 17:10:34,156 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 17:10:34,165 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 17:10:34,245 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-11 17:10:34,252 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 17:10:34,262 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 17:10:34,280 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'top';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 17:10:34,281 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 17:12:07,925 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 17:12:07,934 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 17:12:07,948 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set deadlock_timeout to '0';" to update dbms for error: 0 ms is outside the valid range for parameter "deadlock_timeout" (1 .. 2147483647)

[2025-04-11 17:12:08,022 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 17:12:08,032 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 17:12:08,050 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'all';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 17:12:08,050 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 17:12:28,262 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 17:12:51,808 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 17:12:51,817 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 17:12:51,912 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 17:12:51,923 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 17:12:51,942 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'all';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 17:12:51,942 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 17:14:22,640 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 17:14:22,654 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 17:14:22,756 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 17:14:22,768 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 17:14:22,789 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'all';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 17:14:22,789 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 17:15:53,644 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 17:15:53,666 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 17:15:53,940 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 17:15:53,969 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 17:15:54,026 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'all';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 17:15:54,026 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 17:16:14,304 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 17:16:38,070 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 17:16:38,078 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'on';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 17:16:38,091 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set deadlock_timeout to '0';" to update dbms for error: 0 ms is outside the valid range for parameter "deadlock_timeout" (1 .. 2147483647)

[2025-04-11 17:16:38,182 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 17:16:38,202 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'top';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 17:16:38,202 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 17:18:26,273 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 17:18:26,280 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 17:18:26,373 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 17:18:26,383 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 17:18:26,401 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'all';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 17:18:26,401 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 17:20:04,798 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 17:20:04,807 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'on';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 17:20:04,820 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set deadlock_timeout to '0';" to update dbms for error: 0 ms is outside the valid range for parameter "deadlock_timeout" (1 .. 2147483647)

[2025-04-11 17:20:04,914 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 17:20:04,934 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'all';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 17:20:04,935 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 17:22:05,505 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 17:22:05,514 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 17:22:05,529 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set deadlock_timeout to '0';" to update dbms for error: 0 ms is outside the valid range for parameter "deadlock_timeout" (1 .. 2147483647)

[2025-04-11 17:22:05,606 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 17:22:05,616 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 17:22:05,635 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'all';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 17:22:05,635 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 17:23:44,048 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 17:23:44,056 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 17:23:44,163 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 17:23:44,182 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'all';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 17:23:44,183 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 17:25:22,669 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 17:25:22,681 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 17:25:22,802 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 17:25:22,821 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'all';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 17:25:22,822 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 17:27:00,618 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 17:27:00,626 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 17:27:00,639 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set deadlock_timeout to '0';" to update dbms for error: 0 ms is outside the valid range for parameter "deadlock_timeout" (1 .. 2147483647)

[2025-04-11 17:27:00,709 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-11 17:27:00,716 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 17:27:00,727 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 17:27:00,745 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'all';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 17:27:00,746 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 17:27:21,029 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 17:27:44,681 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 17:27:44,690 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 17:27:44,792 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 17:27:44,811 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'all';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 17:27:44,812 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 17:29:23,431 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 17:29:23,440 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'on';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 17:29:23,532 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-11 17:29:23,554 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '160069413';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 17:29:23,576 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'all';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 17:29:23,577 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 17:29:45,742 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 17:30:09,659 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 17:30:09,667 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 17:30:09,755 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 17:30:09,765 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 17:30:09,784 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'top';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 17:30:09,784 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 17:31:48,689 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 17:31:48,697 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 17:31:48,784 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 17:31:48,794 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 17:31:48,812 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'top';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 17:31:48,812 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 17:33:27,648 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 17:33:27,657 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 17:33:27,669 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set deadlock_timeout to '0';" to update dbms for error: 0 ms is outside the valid range for parameter "deadlock_timeout" (1 .. 2147483647)

[2025-04-11 17:33:27,762 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 17:33:27,785 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'all';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 17:33:27,786 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 17:35:06,774 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 17:35:06,783 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 17:35:06,873 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 17:35:06,882 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 17:35:06,900 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'top';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 17:35:06,901 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 17:35:06,901 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-11 17:36:41,796 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 17:36:41,805 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'on';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 17:36:41,885 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-11 17:36:41,904 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 17:36:41,922 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'all';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 17:36:41,923 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 17:37:02,145 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 17:37:25,846 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 17:37:25,854 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'on';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 17:37:25,868 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set deadlock_timeout to '0';" to update dbms for error: 0 ms is outside the valid range for parameter "deadlock_timeout" (1 .. 2147483647)

[2025-04-11 17:37:25,934 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-11 17:37:25,952 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '818620910';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 17:37:25,973 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'top';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 17:37:25,974 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 17:37:46,194 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 17:38:09,962 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 17:38:09,970 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 17:38:10,071 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 17:38:10,082 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 17:38:10,102 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'all';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 17:38:10,102 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 17:38:10,103 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-11 17:39:44,491 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 17:39:44,499 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'on';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 17:39:44,610 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 17:39:44,634 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'none';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 17:39:44,635 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 17:40:04,966 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 17:40:28,640 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 17:40:28,649 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 17:40:28,664 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set deadlock_timeout to '0';" to update dbms for error: 0 ms is outside the valid range for parameter "deadlock_timeout" (1 .. 2147483647)

[2025-04-11 17:40:28,750 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '947041593';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 17:40:28,773 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'all';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 17:40:28,773 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 17:40:28,774 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-11 17:40:50,908 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 17:41:14,576 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 17:41:14,597 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 17:41:14,637 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set deadlock_timeout to '0';" to update dbms for error: 0 ms is outside the valid range for parameter "deadlock_timeout" (1 .. 2147483647)

[2025-04-11 17:41:14,856 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 17:41:14,885 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 17:41:14,941 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'top';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 17:41:14,942 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 17:42:53,044 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 17:42:53,051 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 17:42:53,150 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 17:42:53,168 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'top';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 17:42:53,169 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 17:44:49,560 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 17:44:49,569 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 17:44:49,583 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set deadlock_timeout to '0';" to update dbms for error: 0 ms is outside the valid range for parameter "deadlock_timeout" (1 .. 2147483647)

[2025-04-11 17:44:49,642 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-11 17:44:49,648 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 17:44:49,658 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 17:44:49,683 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'top';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 17:44:49,684 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 17:44:49,684 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-11 17:45:09,924 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 17:45:33,657 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 17:45:33,665 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 17:45:33,755 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 17:45:33,765 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '10000';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 17:45:33,785 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'top';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 17:45:33,785 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 17:47:16,953 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 17:47:16,960 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 17:47:17,033 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-11 17:47:17,039 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 17:47:17,049 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '298020106';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 17:47:17,067 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'all';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 17:47:17,067 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 17:48:48,628 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 17:48:48,640 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'on';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 17:48:48,730 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 17:48:48,739 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 17:48:48,759 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'top';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 17:48:48,759 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 17:50:27,171 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 17:50:27,179 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 17:50:27,194 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set deadlock_timeout to '0';" to update dbms for error: 0 ms is outside the valid range for parameter "deadlock_timeout" (1 .. 2147483647)

[2025-04-11 17:50:27,288 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 17:50:27,307 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'top';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 17:50:27,307 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 17:50:49,536 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 17:51:13,216 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 17:51:13,224 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'on';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 17:51:13,237 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set deadlock_timeout to '0';" to update dbms for error: 0 ms is outside the valid range for parameter "deadlock_timeout" (1 .. 2147483647)

[2025-04-11 17:51:13,312 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 17:51:13,323 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 17:51:13,343 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'top';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 17:51:13,344 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 17:52:52,228 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 17:52:52,236 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 17:52:52,318 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-11 17:52:52,325 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 17:52:52,337 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 17:52:52,356 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'top';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 17:52:52,357 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 17:54:30,807 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 17:54:30,816 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'on';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 17:54:30,905 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 17:54:30,916 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 17:54:30,936 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'top';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 17:54:30,936 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 17:56:02,138 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 17:56:02,147 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'on';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 17:56:02,160 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set deadlock_timeout to '0';" to update dbms for error: 0 ms is outside the valid range for parameter "deadlock_timeout" (1 .. 2147483647)

[2025-04-11 17:56:02,225 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-11 17:56:02,232 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 17:56:02,243 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '790329206';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 17:56:02,265 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'all';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 17:56:02,266 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 17:56:22,524 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 17:56:46,252 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 17:56:46,261 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'on';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 17:56:46,276 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set deadlock_timeout to '0';" to update dbms for error: 0 ms is outside the valid range for parameter "deadlock_timeout" (1 .. 2147483647)

[2025-04-11 17:56:46,363 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 17:56:46,383 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'all';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 17:56:46,384 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 17:58:24,901 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 17:58:24,909 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'on';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 17:58:24,922 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set deadlock_timeout to '0';" to update dbms for error: 0 ms is outside the valid range for parameter "deadlock_timeout" (1 .. 2147483647)

[2025-04-11 17:58:25,000 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 17:58:25,010 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 17:58:25,028 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'all';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 17:58:25,029 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 17:58:25,029 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-11 17:58:45,271 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-11 17:59:09,013 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 17:59:09,020 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 17:59:09,115 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 17:59:09,125 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 17:59:09,144 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'none';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 17:59:09,145 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-11 18:00:46,894 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-11 18:00:46,903 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set track_wal_io_timing to 'off';" to update dbms for error: unrecognized configuration parameter "track_wal_io_timing"

[2025-04-11 18:00:47,000 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set effective_io_concurrency to '-1';" to update dbms for error: -1 is outside the valid range for parameter "effective_io_concurrency" (0 .. 1000)

[2025-04-11 18:00:47,010 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.max to '-1';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.max"

[2025-04-11 18:00:47,028 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set pg_stat_statements.track to 'none';" to update dbms for error: unrecognized configuration parameter "pg_stat_statements.track"

[2025-04-11 18:00:47,028 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

